### ISSUE TITLE
Better props example

### ISSUE THREAD

**Issue by conartist6** [ungap/esx#2]
In the README you say:
> `props doesn't need ${...props} or ...${props} //  because any value can be passed as interpolation`

That doesn't seem to me to be literally true. I'd expect that in the case of `<tag attr=${value} />` any `value` would be legal. In the case of `<tag ${value} />`, it would seem that not all values would be legal though. `<tag ${2} />` seems like nonsense.

So what is legal? Just `{[attr]: value}` objects? ESX fragments? If it's ESX fragments you'd have to be sure that the fragment is not itself a tag, because `<tag <tag />/>` is also nonsense.

**Comment by conartist6** [comment]
It seems to me that there may well be reason to implement `<tag ...${props} />` as it creates a useful and unambiguous declaration of intent and doesn't open the door to invalid constructions.

**Comment by WebReflection** [comment]
Tokens as attributes make no sense, but you could pass it and deal with it.

`…${any}` is ambiguous, as it can be also part of content where those dots are just part of the text, meaning nothing. I think not needing spread is ok.

**Comment by WebReflection** [comment]
P.S. if you pass a value without being an attribute assignment the assign operation happens, and that’s fine, as that’s exactly what React and others do too. Don’t pass non props or attributes related content, but feel free to.

**Comment by WebReflection** [comment]
Also P.S. this has been discussed in the TC39 proposal. Please read it through to understand the choice made here.

**Comment by WebReflection** [comment]
> <tag ${2} /> seems like nonsense.

as mentioned in the README, it’s not a goal of this proposal to limit developers intent. That is an interpolation as part of attributes with value 2. It’s not on me or you to decide if that makes sense or not, as ESX purpose is to tokenize and don’t impose any opinionated choice behind. The only opinion, because there wouldn’t be ESX otherwise, is to provide tokens in a JSX *like* syntax, not to tell developers what to do with tokens. When it comes to the current known React influenced world, 2 as props makes no sense, but props here are just a backward compatible helper to satisfy current expectations, although attributes are completely free from expectations or caveats, allowing developers to explore better alternative to the current JSX de-facto standard, as that’s also going nowhere.

**Comment by conartist6** [comment]
I don't understand. Ensuring your tokens make up a basic kind of syntax isn't the same as telling developers how to use the syntax. XML has clear syntactic rules: `<a 2 />` is not valid XML. So what would be the point in ensuring that it's possible for XML like this to be produced specifically when XML-like syntax is written in a javascript template tag?

**Comment by conartist6** [comment]
If your parser rejects that static syntax, and it should reject any dynamic interpolation that would lead to a syntactically incorrect structure that could not be understood as a collection of nodes, children, and attributes.

**Comment by conartist6** [comment]
With this reasoning I see no problem with  `<a ...${props} />` because `<a ... />` is not valid XML, therefore there is no ambiguity.

**Comment by conartist6** [comment]
It's particularly important because if you don't forbid invalid syntax you'll never be able to extend your syntax at all!

**Comment by WebReflection** [comment]
ESX is not XML … it’s JSX, which is also neither XML nor JS. ESX doesn’t sanitize anything, it leverages developers intent and it represents tokens. If a developer wants to use 2 statically that’s ignored. If a developer wants to use 2 as explicit interpolation intent, that’s represented by the tokenizer.

**Comment by WebReflection** [comment]
This is also described in the README in the about section, so I hope the goal scope of this project is clear. ESX is a tokenizer, not HTML, not XML, it tokenizes JSX **like** syntax. As this is discussed in TC39 proposal and clarified in the README, I might improve that part to clarify further, but I won’t change ESX goals. Accordingly, I think there’s no action for me to take in here.

**Comment by conartist6** [comment]
I see, that does clarify a bit.

**Comment by WebReflection** [comment]
To close this: ESX in here will never sanitize as a whole parser would make it unusable, slow, and bloated for no real-world need or use case. Anything else can be discussed as TC39 proposal, and this library will adjust when, or if ever, needed, just like any transformer or tokenizer. It won’t happen in here at this point though, but I might relax the RegExp around attributes to ignore … that’s still not sanitizing anything, it would just accomodate people believing … in attributes are needed. To me that’s just ambiguous syntax out of template literals, and it brings nothing to the plate. FYI in JSX you can spread even a function without errors, and props will fail your expectations. That’s it, spreading limits ESX, and I don’t like it.

**Comment by WebReflection** [comment]
To whom it might concern, it's important to realize that `<element ...${spread} />` *can* be written *but* there won't be any extra information that it was a `spread` operation. Anything in attributes that's not an assignment gets discarded.
