### ISSUE TITLE
Eliminate template tag or make it parse

### ISSUE THREAD

**Issue by conartist6** [ungap/esx#3]
I don't have a problem with ESX as a proposal being built around a core of tokenization, but in creating a library with a template tag implementation you've implied that you provide parsing. If you don't provide any guarantee of suitability for parsing then no syntax highlighter can or should ever support highlighting syntax inside your template tag. A template tag implementation can and should be built around your tokenizer core, but there's little point to a tokenizer that isn't at all structurally aware having a template tag.

**Comment by conartist6** [comment]
If you want I'm willing to write you a parser. It's kind of what I do.

**Comment by conartist6** [comment]
If you're curious here's an example of a [regex-based matcher](https://github.com/conartist6/pupa/blob/17f43fa78e84f7344b583718ea2d374e70e77454/index.js) that I replaced with [a parser](https://github.com/conartist6/pupa/blob/7bcd114a709571e28c081815cb032516505b43af/index.js).

**Comment by WebReflection** [comment]
> in creating a library with a template tag implementation you've implied that you provide parsing

I've written template literals based libraries for 5+ years now ... none of them imply parsing.

> If you don't provide any guarantee of suitability for parsing then no syntax highlighter can or should ever support highlighting syntax inside your template tag

[my extension works great](https://marketplace.visualstudio.com/items?itemName=webreflection.literally-html) and so does [JSX applied to ESX](https://github.com/ungap/babel-plugin-transform-esx#readme) so I am not sure what you are saying.

> allowing unparseable static text like <tag $+$ /> or who knows what else.

that's simply ignored *but* a JSX like highlighter would warn you there's an error there, and that's indeed not possible with ESX as Babel transformer so I am not sure I am following what is the issue.

> If you're curious here's an example of ...

both bloated compared to current implementation which works just fine.

**Comment by conartist6** [comment]
> the goal of esx as template literal tag is to have exactly the same parser used for JSX but within template tags. Nothing more, nothing less.

I don't understand what we disagree about then! `<a $ />` is completely invalid JSX. It blows up the babel parser.  It needs to blow up this parser as well!

**Comment by WebReflection** [comment]
> I don't understand what we disagree about then! <a $ /> is completely invalid JSX

you want this to be fixed by the library ... I say fix it with the tools ... that's where we disagree!

**Comment by conartist6** [comment]
The reason your parsing-html-with-regex approach works fine on a babel transform is that there you're using it on syntax that has already been parsed by the babel parser. You don't have to consider dealing with any cases of malformed syntax because by the time your code runs they don't exist!

You just don't seem to think that that provided anyone any value. I strongly disagree.

**Comment by WebReflection** [comment]
in short, this library will do everything possible to be the smallest / fastest thing out there ... any proposal to do what pre-parsing/IDE tools do, will be happily ignored

**Comment by conartist6** [comment]
OK, then I'm going to release a competing tool that has strict parsing and thus forwards and sideways compatibility, and people are going to want to use mine over yours...

**Comment by WebReflection** [comment]
@conartist6 be my guest 👋
